### ISSUE TITLE
error when install this moduls in odoo10

### ISSUE THREAD

**Issue by vijay-huang** [Pravithavarghese1/hr_biometric_machine#15]
when i install hr_biometric_machine in odoo10  , it show me the error as below:

Traceback (most recent call last):
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/Users/vijayhuang/OdooSource/odoo-demo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/vijayhuang/OdooSource/odoo-demo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/tools/convert.py", line 834, in convert_file
    fp = file_open(pathname)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/tools/misc.py", line 195, in file_open
    return _fileopen(name, mode=mode, basedir=rtp, pathinfo=pathinfo, basename=basename)
  File "/Users/vijayhuang/OdooSource/odoo-demo/odoo/tools/misc.py", line 242, in _fileopen
    raise IOError('File not found: %s' % basename)
IOError: File not found: hr_biometric_machine/demo/demo.xml

**Comment by Pravithavarghese1** [comment]
Dear vijayhuang,
Any queries or issues post it here or to pravithavarghese1@gmail.com.

**Comment by Pravithavarghese1** [comment]
have you installed hr_attendance before installing hr_biometric machine?

**Comment by Pravithavarghese1** [comment]
Demo file is not needed in the module so I have commented it out, please download the new commit and try to install. Any further issues please post it here. This is a module under development.

**Comment by shabeervpk** [comment]
@Pravithavarghese1 Hi,
Nice job, tried this module. But my device is **ZKTeco iFace 990** , i think it is not compatible with the zklib you are using in this module.
Do you have any suggestions to integrate the same device with my odoo (working in Ubuntu server)
What are the devices which are compatible with this module (with  zklib)

Thanks,
Shabeer

**Comment by Pravithavarghese1** [comment]
May be you can recode this module using  'pyzk'   link:[https://pypi.python.org/pypi/pyzk/0.5](https://pypi.python.org/pypi/pyzk/0.5)
