### ISSUE TITLE
Invalid model name u'biometric.machine' in action definition. None" while parsing 

### ISSUE THREAD

**Issue by ghost** [Pravithavarghese1/hr_biometric_machine#3]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 638, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 675, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 331, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 119, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 324, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 933, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 504, in response_wrap
  File "D:\odoo\addons\web\controllers\main.py", line 866, in call_button
  File "D:\odoo\addons\web\controllers\main.py", line 854, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 681, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 672, in call_kw_multi
  File "D:\odoo\odoo\addons\base\module\module.py", line 410, in button_immediate_install
  File "D:\odoo\odoo\addons\base\module\module.py", line 484, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\registry.py", line 78, in new
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 337, in load_modules
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 235, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 156, in load_module_graph
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 95, in _load_data
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 848, in convert_file
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 918, in convert_xml_import
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 799, in parse
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 802, in parse
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 710, in _tag_record
  File "D:\odoo\odoo\addons\base\ir\ir_model.py", line 1180, in _update
  File "D:\odoo\odoo\addons\base\ir\ir_actions.py", line 340, in create
  File "D:\odoo\odoo\addons\base\ir\ir_actions.py", line 40, in create
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 3804, in create
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 3960, in _create
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 1065, in _validate_fields
  File "D:\odoo\odoo\addons\base\ir\ir_actions.py", line 248, in _check_model
ParseError: "Invalid model name u'biometric.machine' in action definition.
None" while parsing file:///D:/odoo/addons/hr_biometric_machine/views/biometric_machine_view.xml:46, near
<record id="open_view_attendance_machine" model="ir.actions.act_window">
            <field name="name">Attendances</field>
            <field name="res_model">biometric.machine</field>
            <field name="view_type">form</field>
            <field name="view_mode">tree,form</field>
        </record>

**Comment by Pravithavarghese1** [comment]
The module is perfectly working for me without any error.

**Comment by ghost** [comment]
i am run with odoo 10 ... when i am install the module ... ParseError: "Invalid model name u'biometric.machine' in action definition....

**Comment by Pravithavarghese1** [comment]
have you installed 'hr_attendance' before installing 'hr_biometric_machine'?

**Comment by ghost** [comment]
i am no have installed hr_attendance because hr_attendance automaticaly installed when i am installed module hr_biometric_machine...

**Comment by Pravithavarghese1** [comment]
try installing hr_attendance first and then hr_biometric_machine.

**Comment by ghost** [comment]
thanks ...solved i can success install....

**Comment by Pravithavarghese1** [comment]
your welcome
